---
- name: Compress directory civiReconciler into civiReconciler.zip
  shell: "zip -r civiReconciler.zip civiReconciler"
  become: no
  run_once: true
  delegate_to: 127.0.0.1
  args:
    chdir: "{{ playbook_dir }}/../../"
- name: example copying file with owner and permissions
  copy:
    src: "{{ playbook_dir }}/../../civiReconciler.zip"
    dest: /tmp/civiReconciler.zip
- name: Install zip packages
  apt:
    name: "{{ item }}"
    state: latest 
  with_items:
    - unzip
    - zip
- name: unzip civiReconciler
  shell: unzip civiReconciler.zip -d /var/www
  args:
    chdir: "/tmp"
- name: Install Composer deps
  composer:
    command: install
    working_dir: /var/www/civiReconciler
- name: Optimize Configuration loading and routes
  shell: "{{ item }}"
  args:
    chdir: "/var/www/civiReconciler"
  with_items:
    - php artisan config:cache
    # - php artisan route:cache
    # Routes need to be converted from closures to Controller references before this will work (aka: TODO)
- name: Install nginx
  apt:
    name: nginx
    state: latest 
- name: Copy over nginx conf for Laravel
  template:
    src: "{{ playbook_dir }}/templates/nginx/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf 
- name: Copy over php-fpm conf for Laravel
  copy:
    src: "{{ playbook_dir }}/files/php-fpm/php-fpm.conf"
    dest: /etc/php-fpm.conf 
- name: Install nodejs
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - npm

 