---
# PHP UPGRADE REF: https://thishosting.rocks/install-php-on-ubuntu/
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Install python software properties
  apt:
    name: python-software-properties
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Add on PHP repo
  apt_repository:
    repo: 'ppa:ondrej/php'  
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Update php to the latest version
  apt:
    name: php7.2
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deploy
- name: Add PHP additions
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
    - php-pear 
    - php7.2-curl 
    - php7.2-dev 
    - php7.2-gd 
    - php7.2-mbstring 
    - php7.2-zip 
    - php7.2-mysql 
    - php7.2-xml
  tags:
    - deploy
- name: Setup PHP Composer
  shell: curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  tags:
    - deploy
# add-apt-repository ppa:nginx/stable

