---
- name: Compress directory civiReconciler into civiReconciler.zip
  shell: "zip -r {{ playbook_dir }}/../../civiReconciler.zip {{ playbook_dir }}/../../civiReconciler"
  become: no
  delegate_to: 127.0.0.1