---
- name: Compress directory civiReconciler into civiReconciler.zip
  shell: "zip -r civiReconciler.zip civiReconciler"
  become: no
  run_once: true
  delegate_to: 127.0.0.1
  args:
    chdir: "{{ playbook_dir }}/../../"
- name: example copying file with owner and permissions
  copy:
    src: "{{ playbook_dir }}/../../civiReconciler.zip"
    dest: /tmp/civiReconciler.zip
- name: Install zip packages
  apt:
    name: "{{ item }}"
    state: latest 
  with_items:
    - unzip
    - zip
- name: unzip civiReconciler
  shell: unzip civiReconciler.zip -d /var/www
  args:
    chdir: "/tmp"
- name: Setup the .env file
  template:
    src: "{{ playbook_dir }}/templates/env.j2"
    dest: "/var/www/civiReconciler/.env"
- name: Install Composer deps
  composer:
    command: install
    working_dir: /var/www/civiReconciler
- name: Optimize Configuration loading and routes
  shell: "{{ item }}"
  args:
    chdir: "/var/www/civiReconciler"
  with_items:
    - php artisan config:cache
    # - php artisan route:cache
    # Routes need to be converted from closures to Controller references before this will work (aka: TODO)
- name: Install nodejs dependencies
  shell: "{{ item }}"
  args:
    chdir: "/var/www/civiReconciler"
  with_items:
    - npm install
    - "npm run {{ 'production' if deploy_env == 'Production' else 'development' }}"
- name: Change owner and group of laravel
  file: 
    dest: /var/www/civiReconciler
    owner: www-data 
    group: www-data
    recurse: yes  
- name: Setup Runit services
  include: runit.yml
  tags:
    - deploy 
