---
- name: Compress directory civiReconciler into civiReconciler.zip
  shell: "zip -r {{ playbook_dir }}/../../civiReconciler.zip {{ playbook_dir }}/../../civiReconciler"
  become: no
  run_once: true
  delegate_to: 127.0.0.1
- name: example copying file with owner and permissions
  copy:
    src: "{{ playbook_dir }}/../../civiReconciler.zip"
    dest: /tmp/civiReconciler.zip
- name: Install zip packages
  apt:
    name: "{{ item }}"
    state: latest 
  with_items:
    - unzip
    - zip
- name: unzip civiReconciler
  shell: unzip civiReconciler.zip
  args:
    chdir: "/tmp"