---
- name: Install development tools
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc 
    - g++ 
    - make
    - build-essential
- name: Execute the nodejs setup script
  shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -
- name: Setup yarn
  shell: "{{ item }}"
  with_items:
    - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
- name: Install nodejs
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - yarn
    
    
