---
- hosts: "{{ target_hosts }}"
  gather_facts: "{{ gather_facts|default(true)|bool }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  vars:
    php_version: php7.2
    app_name: "{{ lookup('ini', 'appBaseName type=properties file=../gradle.properties') }}"
    app_version: "{{ lookup('ini', 'appVersion type=properties file=../gradle.properties') }}"
  environment:
    PYTHONPATH: "{{ playbook_dir }}/roles/libs/lib/python2.7/site-packages/"
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-virtualenv python-pip sudo)
      when: "gather_facts|default(true)|bool == false"
      tags:
        - deploy      
    - setup: # aka gather_facts
      when: "gather_facts|default(true)|bool == false"
      tags:
        - deploy   
  roles:
    - { role: phusionssl, tags: ["deploy"] }
    - { role: authorizedkeys, tags: ["deploy"] }
    - { role: ubuntunodejs, node_version: "10", tags: ["deploy"] }
    - { role: ubuntunginx, tags: ["deploy"] }
    - { role: ubuntuphp, tags: ["deploy"] }
    - { role: ymdpuppetclient, tags: ["deploy"] }
    - { role: ymddockerpy, tags: ["provision","deploy"] }
    - { role: ymdfpm, tags: ["deploy"] }
  tasks:
    - name: Provision VoterListRegistry
      include: provision.yml
      tags:
        - provision
    - name: Deploy VoterListRegistry
      include: deploy.yml
      tags:
        - deploy
