---
- name: virtualenv activate
  shell: ". {{ dockerpy_virtualenv_activatepath }}"   
  tags:
    - provision    
- name: recreate a container
#  docker_container: (2.4x syntax)
  docker:
    name: "{{ item }}"
    hostname: "{{ item }}"
    image: phusion/baseimage:0.10.1
    state: reloaded
    # state: started    
    # recreate: yes
    command: "/sbin/my_init"
    # command: ["sleep", "infinity"]
    ports: 
      - 80:81
      - 22:22
    links:
      - "{{ groups[hostvars[item]['vlrhost']][0] }}:{{ groups[hostvars[item]['vlrhost']][0].split('.')[0] }}"
  with_items: "{{ groups[group_hosts] }}"
  environment:
    PYTHONPATH: "{{ dockerpy_pythonpath }}"
  tags:
    - provision    
    
    

