---
- src: ymdgit:ymd-ansible-inventory.git
  version: master
  scm: git
  name: inventory
- src: ymdgit:ymd-authorizedkeys.git
  version: master
  scm: git
  name: authorizedkeys
- src: ymdgit:ymd-phusion-ssl-role.git
  version: master
  scm: git
  name: phusionssl
- src: ymdgit:ymd-ubuntu-php-role.git
  version: master
  scm: git
  name: ubuntuphp
- src: ymdgit:ymd-ubuntu-nodejs.git
  version: master
  scm: git
  name: ubuntunodejs
