---
- name: Copy over nginx conf for Laravel
  template:
    src: "{{ playbook_dir }}/templates/nginx/nginx.conf.j2"
    dest: /etc/nginx/sites-available/default 
#- name: Copy over php-fpm conf for Laravel
#  copy:
#    src: "{{ playbook_dir }}/files/php-fpm/php-fpm.conf"
#    dest: /etc/php-fpm.conf 
- name: create runit folders
  file:
    path: "/etc/service/{{ item }}"
    state: directory
  with_items:
    - nginx
    - phpfpm
  tags:
    - deploy    
- name: Copy over nginx runit file
  copy:
    src: "{{ playbook_dir }}/files/runit/{{ item }}"
    dest: "/etc/service/{{ item | splitext | first }}/run"
    owner: root
    group: root
    mode: 0755
  with_items:
    - nginx.sh
  tags:
    - deploy 
- name: Copy over phpfpm runit file
  template:
    src: "{{ playbook_dir }}/templates/runit/{{ item }}"
    dest: "/etc/service/{{ item | splitext | first | splitext | first }}/run"
    owner: root
    group: root
    mode: 0755
  with_items:
    - phpfpm.sh.j2
  tags:
    - deploy 
